"""Added Ticket Service

Revision ID: 479e3415f1a2
Revises: 
Create Date: 2024-03-10 22:24:59.170174

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "479e3415f1a2"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticket",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column(
            "state",
            sa.Enum("DRAFT", "POSTED", "DONE", name="ticketstate"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("start_num", sa.Integer(), nullable=False),
        sa.Column("end_num", sa.Integer(), nullable=False),
        sa.Column("win_num", sa.Integer(), nullable=True),
        sa.Column("available_count", sa.Integer(), nullable=False),
        sa.Column("reserved_count", sa.Integer(), nullable=False),
        sa.Column("sold_count", sa.Integer(), nullable=False),
        sa.Column("sync_user", sa.String(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("write_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_create_date"), "ticket", ["create_date"], unique=False
    )
    op.create_index(op.f("ix_ticket_state"), "ticket", ["state"], unique=False)
    op.create_index(op.f("ix_ticket_sync_user"), "ticket", ["sync_user"], unique=False)
    op.create_index(
        op.f("ix_ticket_write_date"), "ticket", ["write_date"], unique=False
    )
    op.create_table(
        "ticket_order",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=15), nullable=False),
        sa.Column(
            "state",
            sa.Enum("DRAFT", "CANCEL", "SUCCESSFUL", "VARIFIED", name="orderstate"),
            nullable=False,
        ),
        sa.Column("user_code", sa.String(length=32), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("write_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_order_create_date"),
        "ticket_order",
        ["create_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_order_name"), "ticket_order", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_order_state"), "ticket_order", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_order_user_code"), "ticket_order", ["user_code"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_order_write_date"), "ticket_order", ["write_date"], unique=False
    )
    op.create_table(
        "ticket_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column("user_code", sa.String(length=30), nullable=True),
        sa.Column("is_special_price", sa.Boolean(), nullable=False),
        sa.Column("special_price", sa.Float(), nullable=False),
        sa.Column(
            "state",
            sa.Enum("AVAILABLE", "RESERVED", "SOLD", name="ticketlinestate"),
            nullable=False,
        ),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("write_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["ticket.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_line_create_date"), "ticket_line", ["create_date"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_line_state"), "ticket_line", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_line_ticket_id"), "ticket_line", ["ticket_id"], unique=False
    )
    op.create_index(
        op.f("ix_ticket_line_write_date"), "ticket_line", ["write_date"], unique=False
    )
    op.create_table(
        "ticket_order_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("ticket_line_id", sa.Integer(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("write_date", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["ticket_order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ticket_line_id"],
            ["ticket_line.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_order_line_create_date"),
        "ticket_order_line",
        ["create_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_order_line_order_id"),
        "ticket_order_line",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_order_line_ticket_line_id"),
        "ticket_order_line",
        ["ticket_line_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticket_order_line_write_date"),
        "ticket_order_line",
        ["write_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ticket_order_line_write_date"), table_name="ticket_order_line"
    )
    op.drop_index(
        op.f("ix_ticket_order_line_ticket_line_id"), table_name="ticket_order_line"
    )
    op.drop_index(op.f("ix_ticket_order_line_order_id"), table_name="ticket_order_line")
    op.drop_index(
        op.f("ix_ticket_order_line_create_date"), table_name="ticket_order_line"
    )
    op.drop_table("ticket_order_line")
    op.drop_index(op.f("ix_ticket_line_write_date"), table_name="ticket_line")
    op.drop_index(op.f("ix_ticket_line_ticket_id"), table_name="ticket_line")
    op.drop_index(op.f("ix_ticket_line_state"), table_name="ticket_line")
    op.drop_index(op.f("ix_ticket_line_create_date"), table_name="ticket_line")
    op.drop_table("ticket_line")
    sa.Enum("AVAILABLE", "RESERVED", "SOLD", name="ticketlinestate").drop(op.get_bind())
    op.drop_index(op.f("ix_ticket_order_write_date"), table_name="ticket_order")
    op.drop_index(op.f("ix_ticket_order_user_code"), table_name="ticket_order")
    op.drop_index(op.f("ix_ticket_order_state"), table_name="ticket_order")
    op.drop_index(op.f("ix_ticket_order_name"), table_name="ticket_order")
    op.drop_index(op.f("ix_ticket_order_create_date"), table_name="ticket_order")
    op.drop_table("ticket_order")
    sa.Enum("DRAFT", "CANCEL", "SUCCESSFUL", "VARIFIED", name="orderstate").drop(
        op.get_bind()
    )
    op.drop_index(op.f("ix_ticket_write_date"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_sync_user"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_state"), table_name="ticket")
    op.drop_index(op.f("ix_ticket_create_date"), table_name="ticket")
    op.drop_table("ticket")
    sa.Enum("DRAFT", "POSTED", "DONE", name="ticketstate").drop(op.get_bind())
    # ### end Alembic commands ###
