"""nullable false in start date and end date

Revision ID: b36625a26b41
Revises: fc8193268f20
Create Date: 2024-03-10 23:34:17.729241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b36625a26b41"
down_revision: Union[str, None] = "fc8193268f20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ticket", "start_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "ticket", "end_date", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ticket", "end_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "ticket", "start_date", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    # ### end Alembic commands ###
