"""Added start date and end date

Revision ID: fc8193268f20
Revises: 479e3415f1a2
Create Date: 2024-03-10 23:32:21.623140

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc8193268f20"
down_revision: Union[str, None] = "479e3415f1a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ticket", sa.Column("start_date", sa.DateTime(), nullable=True))
    op.add_column("ticket", sa.Column("end_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ticket", "end_date")
    op.drop_column("ticket", "start_date")
    # ### end Alembic commands ###
