# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Dream Ticket(Python)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    container: lwinmgmg/poetry:3.11.8-1.8.0
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Installation
      run: poetry install
    - name: Pylint
      run: poetry run pylint ticket
    - name: Flake8
      run: poetry run flake8 .

  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    container: lwinmgmg/poetry:3.11.8-1.8.0
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Installation
      run: poetry install
    - name: Pytest
      run: poetry run pytest .
